In [48]:
from jax import grad
import jax.numpy as np
from jax.numpy import linalg as la
import numpy as nnp
import math

In [20]:
class TT_Tensor:
    def __init__(self, core, d, n, r):
        self.core = core
        self.d = d
        self.n = n
        self.r = r

In [33]:
def tt_svd(A, eps):
    d = len(A.shape)
    N = np.size(A)
    n = A.shape

    C = A # tmp tensor

    G = [] # tt-cores
    r = [] # tt-ranks
    r.append(1)

    for k in range(1, d):
        C = np.reshape(C, (r[k-1] * n[k-1], int(N / (r[k-1] * n[k-1]))))
  
        # calc low-rank approximation
        u, s, v = la.svd(C)
        sum = 0 
        nsize = np.size(s)
        rres = np.size(s)
        for rk in range(0, nsize):
            for m in range(rk+1, nsize):
                sum = sum + (s[m] ** 2)
            if (sum <= (eps ** 2) * la.norm(A)) and (rres > rk):
                rres = rk + 1 
            sum = 0
        r .append(rres) 

        G.append(np.reshape(u[:, :r[k]], (r[k-1], n[k-1], r[k])))
        s = np.diag(s)
        C = np.dot(s[:r[k], :r[k]], v[:r[k], :])
        N = (N * r[k]) / (n[k-1] * r[k-1])
    
    if len(C.shape) == 2:
        C = np.reshape(C, (C.shape[0], C.shape[1], 1))
        r.append(C.shape[2])
        
    G.append(C)
    
    return TT_Tensor(G, d, n, r)

In [22]:
def tt_to_tensor(tt, shape):
    G = tt.core
    B = G[0]
    for i in range(1, len(G)):
        X = np.reshape(G[i], (G[i].shape[0], G[i].shape[1] * G[i].shape[2]))
        B = np.reshape(B, (int(np.size(B) / G[i].shape[0]), G[i].shape[0]))
        B = np.dot(B, X)
    B = np.reshape(B, shape)
    return B

In [55]:
def tt_sum(tt1, tt2):
    if tt1.d == tt2.d:
        d = tt1.d
    else:
        raise Exception("Different dimensions of tensors.")
    
    r = [r1 + r2 for r1, r2 in zip(tt1.r, tt2.r)]
    
    if tt1.r[0] == tt2.r[0]:
        r[0] = tt1.r[0]
    else:
        raise Exception("Different sizes of first mode.")
        
    if tt1.r[d] == tt2.r[d]:
        r[d] = tt1.r[d]
    else:
        raise Exception("Different sizes of last mode.")
        
    n = tt1.n
    G = []
    
    for i in range(0, d):
        Gi = nnp.zeros((r[i], n[i], r[i+1]))
        Gi[0 : tt1.r[i], :, 0 : tt1.r[i+1]] = tt1.core[i]
        Gi[r[i] - tt2.r[i] : r[i], :, r[i+1] - tt2.r[i+1]: r[i+1]] = tt2.core[i]   
        G.append(Gi)
    
    return TT_Tensor(G, d, n, r)
    

In [57]:
# input tensor A
'''
A = np.array([[1/2, 1/3, 1/4], [1/3, 1/4, 1/5], [1/4, 1/5, 1/6]])
A = np.arange(24)
B = A.reshape(4, 3, 2)
A = B
'''

'''
A = np.ones(24)
A = A.reshape(4, 3, 2)
'''

A = []
for i in range(4):
  for j in range(3):
    for q in range(2):
      A.append(1 / (i + j + q + 3))
A = np.asarray(A)
A = A.reshape(4, 3, 2)

print("A:\n", A)

eps = 1e-2 # accuracy

tt = tt_svd(A, eps)

for X in tt.core:
    print("\nCore:\n", X, "\nShape: ", X.shape)

print("\nRanks: ", tt.r)

B = tt_to_tensor(tt, A.shape)
print("\nB:\n", B)

tts = tt_sum(tt, tt)
for X in tts.core:
    print("\nCore:\n", X, "\nShape: ", X.shape)

print("\nRanks: ", tts.r)

C = tt_to_tensor(tts, A.shape)
print("\nC:\n", C)

D = B + B
print("\nD:\n", D)



A:
 [[[0.33333334 0.25      ]
  [0.25       0.2       ]
  [0.2        0.16666667]]

 [[0.25       0.2       ]
  [0.2        0.16666667]
  [0.16666667 0.14285715]]

 [[0.2        0.16666667]
  [0.16666667 0.14285715]
  [0.14285715 0.125     ]]

 [[0.16666667 0.14285715]
  [0.14285715 0.125     ]
  [0.125      0.11111111]]]

Core:
 [[[-0.6449674  -0.68758214]
  [-0.5144456   0.09107864]
  [-0.42883325  0.42677027]
  [-0.36805514  0.58034706]]] 
Shape:  (1, 4, 2)

Core:
 [[[-0.6883633   0.40954968]
  [-0.55492496 -0.16872749]
  [-0.46614918 -0.4165662 ]]

 [[-0.02050409  0.66778165]
  [ 0.00807783  0.35927123]
  [ 0.02082663  0.23508413]]] 
Shape:  (2, 3, 2)

Core:
 [[[ 0.704035  ]
  [ 0.57473695]]

 [[-0.01484055]
  [ 0.01817922]]] 
Shape:  (2, 2, 1)

Ranks:  [1, 2, 2, 1]

B:
 [[[0.3332316  0.2501208 ]
  [0.2501208  0.19999859]
  [0.19999862 0.16651078]]

 [[0.2502261  0.19973116]
  [0.19973119 0.16667086]
  [0.16667086 0.14320199]]

 [[0.2000426  0.16661721]
  [0.16661723 0.14285436]
  